name: Deploy with ArgoCD

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_run:
    workflows:
      - "Docker Image CI"
    types:
      - completed
      - success

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with ArgoCD
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          # Add deployment steps for ArgoCD here
        
     
      
