name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build and Test
        run: |
          ls -ltr
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package
      
     # - name: Static Code Analysis
      #  env:
      #    SONAR_URL: http://3.98.125.60:9000
      #  run: |
       #   cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
       #   mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${{ env.SONAR_URL }}

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE: ash7c/ultimate-cicd:${{ github.run_number }}
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          docker build -t ${{ env.DOCKER_IMAGE }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ env.DOCKER_IMAGE }}

      - name: Update Deployment File
        env:
          GIT_REPO_NAME: Jenkins-Zero-To-Hero
          GIT_USER_NAME: ashaf3
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
          sed -i "s/replaceImageTag/${{ github.run_number }}/g" deployment.yml
          git config user.email "ashumysterious007@gmail.com"
          git config user.name "ASH CHAUDHARI"
          git add deployment.yml
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push https://$GITHUB_TOKEN@github.com/${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }} HEAD:main
